version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # The directory where your package.json is located (root)
    schedule:
      interval: "daily"  # Check for updates weekly
    ignore:
      - dependency-name: "react"
        versions: ["^17.0.0"]  # Example: Ignore updates for React 17.x.x
      - dependency-name: "react-dom"
        versions: ["^17.0.0"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"