version: 2
updates:
  # Monitor and update npm dependencies (Node.js/React.js)
  - package-ecosystem: "npm"
    directory: "/"  # The directory where your package.json is located (root)
    schedule:
      interval: "daily"  # Check for updates weekly
