name: Enable Dependabot Alerts

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner of the repository (e.g., user or org name)'
        required: true
        type: string
      repo_name:
        description: 'Name of the repository'
        required: true
        type: string

jobs:
  enable-dependabot-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Enable Dependabot Alerts
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_TOKEN }}
        run: |
          OWNER=${{ github.event.inputs.owner }}
          REPO_NAME=${{ github.event.inputs.repo_name }}
          
          if [ -z "$OWNER" ] || [ -z "$REPO_NAME" ]; then
            echo "Both owner and repository name are required."
            exit 1
          fi

          # Combine owner and repo name
          FULL_REPO_NAME="$OWNER/$REPO_NAME"
          
          # API URL to enable Dependabot Alerts
          API_URL="https://api.github.com/repos/yaksh0210/Exporter_scripts/dependabot/alerts"
          
          # Enable Dependabot Alerts by setting the permissions
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" -d '{"enabled":true}' $API_URL

          echo "Dependabot Alerts have been enabled for $FULL_REPO_NAME"
