name: Set Repository and Organization-Level Secrets and Variables
on:
  workflow_dispatch:
    inputs:
      variable_name_repo:
        description: 'Name of the repository variable'
        required: true
        type: string
      variable_value_repo:
        description: 'Value of the repository variable'
        required: true
        type: string
      secret_name_repo:
        description: 'Name of the repository secret'
        required: true
        type: string
      secret_value_repo:
        description: 'Value of the repository secret'
        required: true
        type: string
jobs:
  set-secrets-and-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set repository-level variable
    - name: Set Repository-Level Variable
      run: |
        echo "Setting repository-level variable..."
        curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.NEW_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"name":"${{ github.event.inputs.variable_name_repo }}", "value":"${{ github.event.inputs.variable_value_repo }}"}' \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/actions/variables/${{ github.event.inputs.variable_name_repo }}

    # Set repository-level secret (must be encrypted first)
    - name: Set Repository-Level Secret
      run: |
        echo "Setting repository-level secret..."
        ENCRYPTED_SECRET=$(echo -n "${{ github.event.inputs.secret_value_repo }}" | openssl enc -aes-256-cbc -base64 -A)
        curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.NEW_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"encrypted_value":"'"$ENCRYPTED_SECRET"'"}' \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/actions/secrets/${{ github.event.inputs.secret_name_repo }}